image: amaysim/serverless:1.25.0

stages:
  - setup
  - build
  - deploy

cache:
  key: "$CI_PIPELINE_ID"

setup:
  stage: setup
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    # Only until the docker image is on 1.26.
    - yarn global add serverless@1.26.0
    - serverless package --stage build

.deploy_template: &deploy_definition
  stage: deploy
  script:
    # Only until the docker image is on 1.26.
    - yarn global add serverless@1.26.0
    - serverless deploy --stage $CI_ENVIRONMENT_NAME --aws-s3-accelerate
  only:
    - master

deploy_unstable:
  <<: *deploy_definition
  environment:
    name: unstable

deploy_public:
  <<: *deploy_definition
  environment:
    name: public
  when: manual
