stages:
- test
- bundle
- package
- deploy

variables:
  AWS_DEFAULT_OUTPUT: text
  SAM_CLI_TELEMETRY: 0

.cache_template:
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
    - ./node_modules/

test-code:
  extends: .cache_template
  image: public.ecr.aws/sam/build-nodejs18.x
  stage: test
  parallel:
    matrix:
    - AUDIENCE: https://api.cimpress.io/
      ISSUERS:
      - https://auth0.cimpress.io/
      - https://cimpress.auth0.com/,https://auth0.cimpress.io/
      - https://cimpress.auth0.com/, https://auth0.cimpress.io/
  before_script:
  - npm ci
  script:
  - npm run test -- --ci --testResultsProcessor='jest-junit'
  cache:
    policy: push
  artifacts:
    reports:
      junit: ./junit.xml

test-template:
  image: public.ecr.aws/sam/build-provided.al2
  stage: test
  before_script:
  - pip install --quiet cfn-lint
  script:
  - sam validate
  - cfn-lint --template ./template.yaml --format junit > ./template.cfn-lint.xml
  artifacts:
    reports:
      junit: ./template.cfn-lint.xml

bundle:
  extends: .cache_template
  image: public.ecr.aws/sam/build-nodejs18.x
  stage: bundle
  script:
  - npm run bundle -- --mode=production
  cache:
    policy: pull
  artifacts:
    paths:
    - ./dist/

bucket:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base
  stage: bundle
  script:
  - export BUCKET="$(aws cloudformation list-exports --query "Exports[?Name=='DeploymentBucket'].Value")"
  - echo "BUCKET=${BUCKET}" >>./bucket.env
  artifacts:
    reports:
      dotenv: ./bucket.env

package:
  image: public.ecr.aws/sam/build-provided.al2
  stage: package
  script:
  - >-
    sam package
    --s3-bucket "${BUCKET}"
    --s3-prefix "${CI_PROJECT_NAME}"
  artifacts:
    paths:
    - ./template.out.yaml

deploy:
  image: public.ecr.aws/sam/build-provided.al2
  stage: deploy
  script:
  - sam publish
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
