stages:
- test
- bundle
- package
- deploy

variables:
  AWS_DEFAULT_OUTPUT: text
  SAM_CLI_TELEMETRY: 0

cache:
  key: "$CI_PIPELINE_ID"

test-code:
  image: node:14-alpine
  stage: test
  variables:
    AUTHORITY: https://cimpress.auth0.com/
  before_script:
  - npm ci
  script:
  - npm run test -- --ci --testResultsProcessor="jest-junit"
  artifacts:
    paths:
    - ./node_modules/
    reports:
      junit: ./junit.xml

test-template:
  image: lambci/lambda:build-provided.al2
  stage: test
  before_script:
  - pip install --quiet cfn-lint
  script:
  - sam validate
  - cfn-lint --template ./template.yaml --format junit > ./template.cfn-lint.xml
  artifacts:
    reports:
      junit: ./template.cfn-lint.xml

bundle:
  image: node:14-alpine
  stage: bundle
  script:
  - npm run bundle -- --mode=production
  artifacts:
    paths:
    - ./dist/

bucket:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: bundle
  script:
  - export BUCKET="$(aws cloudformation list-exports --query "Exports[?Name=='DeploymentBucket'].Value")"
  - echo "BUCKET=${BUCKET}" >>./bucket.env
  artifacts:
    reports:
      dotenv: ./bucket.env

package:
  image: lambci/lambda:build-provided.al2
  stage: package
  script:
  - >-
    sam package
    --s3-bucket "${BUCKET}"
    --s3-prefix "${CI_PROJECT_NAME}"
  artifacts:
    paths:
    - ./template.out.yaml

deploy:
  image: lambci/lambda:build-provided.al2
  stage: deploy
  script:
  - sam publish
  only:
  - main
