image: lambci/lambda:build-nodejs8.10

stages:
  - build
  - package
  - deploy

cache:
  key: "$CI_PIPELINE_ID"

build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - ./dist/

package:
  stage: package
  script:
    - sam package
      --s3-bucket 'deployment-artifacts-eu-west-1-820870426321'
      --s3-prefix 'platform-authorizer'
      --output-template-file ./packaged.yaml
  artifacts:
    paths:
      - ./packaged.yaml

deploy:
  stage: deploy
  script:
    - sam publish --template ./packaged.yaml
  only:
    - master
