image: amaysim/serverless:1.24.0

stages:
  - setup
  - build
  - deploy

cache:
  key: "$CI_PIPELINE_ID"

setup:
  stage: setup
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

.deploy_template: &deploy_definition
  stage: deploy
  script:
    sls deploy -s $CI_ENVIRONMENT_NAME

deploy_develop:
  <<: *deploy_definition
  environment:
    name: develop
  when: manual

deploy_master:
  <<: *deploy_definition
  environment:
    name: master
  when: manual
