stages:
- test
- bundle
- package
- deploy

variables:
  AWS_DEFAULT_OUTPUT: text
  AWS_DEFAULT_REGION: eu-west-1
  AWS_REGION: eu-west-1
  SAM_CLI_TELEMETRY: 0

.cache_template:
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
    - ./src/node_modules/

test-code:
  extends: .cache_template
  image: public.ecr.aws/sam/build-nodejs20.x
  stage: test
  parallel:
    matrix:
    - AUDIENCE: https://api.cimpress.io/
      ISSUERS:
      - https://oauth.cimpress.io/
      - https://cimpress.auth0.com/,https://oauth.cimpress.io/
      - https://cimpress.auth0.com/, https://oauth.cimpress.io/
  before_script:
  - npm --prefix ./src/ ci
  script:
  - npm --prefix ./src/ run test -- --ci --testResultsProcessor='jest-junit'
  cache:
    policy: push
  artifacts:
    reports:
      junit: ./src/junit.xml

test-template:
  image: public.ecr.aws/sam/build-provided.al2023
  stage: test
  before_script:
  - pip install --quiet cfn-lint[junit]
  script:
  - sam validate
  - cfn-lint --template ./template.yaml --format junit > ./template.cfn-lint.xml
  artifacts:
    reports:
      junit: ./template.cfn-lint.xml

bundle:
  extends: .cache_template
  image: public.ecr.aws/sam/build-nodejs20.x
  stage: bundle
  script:
  - sam build
  cache:
    policy: pull
  artifacts:
    paths:
    - ./.aws-sam/

bucket:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base
  stage: bundle
  script:
  - export BUCKET="$(aws cloudformation list-exports --query "Exports[?Name=='DeploymentBucket'].Value")"
  - echo "BUCKET=${BUCKET}" >>./bucket.env
  artifacts:
    reports:
      dotenv: ./bucket.env

package:
  image: public.ecr.aws/sam/build-provided.al2023
  stage: package
  script:
  - >-
    sam package
    --s3-bucket "${BUCKET}"
    --s3-prefix "${CI_PROJECT_NAME}"
    >./template.out.yml
  artifacts:
    paths:
    - ./template.out.yml

deploy:
  image: public.ecr.aws/sam/build-provided.al2023
  stage: deploy
  variables:
    # This component publishes to us-east-1.
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
  script:
  - sam publish --template-file ./template.out.yml
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
