image: amaysim/serverless:1.24.0

stages:
  - setup
  - build
  - deploy

cache:
  key: "$CI_PIPELINE_ID"

setup:
  stage: setup
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - sls package -s build

.deploy_template: &deploy_definition
  stage: deploy
  script:
    - sls deploy -s $CI_ENVIRONMENT_NAME
  only:
    - master

deploy_unstable:
  <<: *deploy_definition
  environment:
    name: unstable

deploy_public:
  <<: *deploy_definition
  environment:
    name: public
  when: manual
