service: Platform-Authorization

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  webpackIncludeModules:
    forceExclude:
      - aws-sdk

plugins:
  - serverless-webpack
  - serverless-plugin-custom-roles
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  versionFunctions: false # Otherwise, deployments would disable every service using this!
  stackTags:
    ROLE: Authorizer

functions:
  Authorizer:
    handler: authorizer.default
    description: Authenticates requests to the Cimpress Mass Customization Platform.
    tracing: true # This is X-Ray.
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'xray:PutTraceSegments'
          - 'xray:PutTelemetryRecords'
        Resource: '*'
  Reporter:
    handler: reporter.default
    description: Reports metrics on the use of the Platform Authorizer.
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'cloudwatch:PutMetricData'
        Resource: '*'
    events:
      - cloudwatchLog:
          logGroup: /aws/lambda/${self:service}-${opt:stage, self:provider.stage}-Authorizer
          filter: '{ $.namespace = "Platform Authorizer" }'

resources:
  Description: A custom authorizer for the Mass Customization Platform.
