service:
  name: Platform-Authorization

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  tracing: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'

  stackTags:
    role: Authorizer

functions:
  Authorizer:
    handler: index.handler
    description: Platform Authorization

resources:
  Description: A custom authorizer for the Mass Customization Platform.
