service: Platform-Authorization

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  webpackIncludeModules:
    forceExclude:
      - aws-sdk

plugins:
  - serverless-webpack
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  versionFunctions: false # Otherwise, deployments would disable every service using this!
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'cloudwatch:PutMetricData'
      Resource: '*'
  stackTags:
    ROLE: Authorizer

functions:
  authorizer:
    handler: authorizer.default
    description: Authenticates requests to the Cimpress Mass Customization Platform.
    tracing: true # This is X-Ray.
  reporter:
    handler: reporter.default
    description: Reports metrics on the use of the Platform Authorizer.
    events:
      - cloudwatchLog:
          logGroup: /aws/lambda/${self:service}-${opt:stage, self:provider.stage}-authorizer
          filter: '{ $.namespace = "Platform Authorizer" }'

resources:
  Description: A custom authorizer for the Mass Customization Platform.
