# license: Apache-2.0

service: Platform-Authorization

frameworkVersion: '>=1.0.0 <2.0.0'

custom:
  webpackIncludeModules:
    forceExclude:
      - aws-sdk

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  versionFunctions: false # Otherwise, deployments would disable every service using this!
  stackTags:
    ROLE: Authorizer

functions:
  Authorizer:
    handler: authorizer.default
    description: Authenticates requests to the Cimpress Mass Customization Platform.
    environment:
      AUDIENCE: https://api.cimpress.io/
      AUTHORITY: https://cimpress.auth0.com/
