# serverless.yml

service:
  name: Platform-Authorization

plugins:
  - serverless-webpack

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stackTags:
    role: Authorizer

functions:
  Authorizer:
    handler: index.handler
    description: Platform Authorization

resources:
  Description: A custom authorizer for the Mass Customization Platform.
