---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: An authentication lambda function for the Cimpress Mass Customization Platform.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: platform-authorizer
    Description: A Lambda Authorizer that can perform authentication for services on the Cimpress Mass Customization Platform.
    Author: Christopher Osborn
    SpdxLicenseId: Apache-2.0
    LicenseUrl: ./LICENSE
    ReadmeUrl: ./README.md
    Labels:
      - auth0
      - oauth2
      - cimpress
      - authentication
      - lambda
      - authorizer
    HomePageUrl: https://github.com/Cimpress-MCP/Platform-Authorizer
    SemanticVersion: 1.0.1
    SourceCodeUrl: https://github.com/Cimpress-MCP/Platform-Authorizer
Parameters:
  Audience:
    Description: The audience which this service is a member of, authenticationally.
    Type: String
    Default: https://api.cimpress.io/
  Authority:
    Description: The source of tokens and the issuer of claims.
    Type: String
    Default: https://cimpress.auth0.com/
    AllowedPattern: ^https:\/\/.+
    ConstraintDescription: Authority must be an HTTPS URL.
Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 5
    MemorySize: 128
    Environment:
      Variables:
        AUDIENCE: !Ref Audience
        AUTHORITY: !Ref Authority
        # note(cosborn) Tokens are valid for the whole stage, so this doesn't need to be restrictive.
        RESOURCE: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*
Resources:
  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: authorizer.default
      Description: A test.
Outputs:
  AuthorizerArn:
    Description: The ARN of the authorizer for the specified stage of the specified API.
    Value: !GetAtt Authorizer.Arn
