---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: An authentication lambda function for the Cimpress Mass Customization Platform.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: platform-authorizer
    Description: A Lambda Authorizer that can perform authentication for services on the Cimpress Mass Customization Platform.
    Author: Christopher Osborn
    SpdxLicenseId: Apache-2.0
    LicenseUrl: ./LICENSE
    ReadmeUrl: ./README.md
    Labels:
    - auth0
    - oauth2
    - cimpress
    - authentication
    - lambda
    - authorizer
    HomePageUrl: https://github.com/Cimpress-MCP/Platform-Authorizer
    SemanticVersion: 2.1.0
    SourceCodeUrl: https://github.com/Cimpress-MCP/Platform-Authorizer
Parameters:
  Audience:
    Description: The audience which this service is a member of, authenticationally.
    Type: String
    Default: https://api.cimpress.io/
  Authority:
    Description: The source of tokens and the issuer of claims.
    Type: String
    Default: https://cimpress.auth0.com/
    AllowedPattern: ^https:\/\/.+
    ConstraintDescription: Authority must be an HTTPS URL.
Resources:
  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: authorizer.default
      Runtime: nodejs10.x
      CodeUri: ./dist
      Description: An API Gateway Lambda Authorizer.
      Environment:
        Variables:
          AUDIENCE: !Ref Audience
          AUTHORITY: !Ref Authority
      Tracing: Active
Outputs:
  AuthorizerArn:
    Description: The ARN of the authorizer for the specified stage of the specified API.
    Value: !GetAtt Authorizer.Arn
